apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: p1
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
    clusterSelector:
      matchLabels:
        project-p1: "true"
  destinations:
  - namespace: '*'
    server: "*"
  sourceRepos:
  - '*'