apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: p2
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
    clusterSelector:
      matchLabels:
        project-p2: "true"
  destinations:
  - namespace: '*'
    server: "*"
  sourceRepos:
  - '*'