apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tests-infra-beta
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: "*"
  sourceRepos:
  - '*'
