apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: configmap-test
      namespace: default
    path: patch.yaml
