resources:
  - configmap-test-mock.yaml
  - existing-service.yaml
patches:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: configmap-test
      namespace: default
    path: patch.yaml
  - target:
      group: ""
      version: v1
      kind: Service
      name: kubernetes
      namespace: default
    path: kubernetes-patch.yaml
