apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-common
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/Shaked/argocd-playground
          revision: main
          files:
            - path: argocd/appsets/operational/infra/cluster-labels/common/**/argo.yaml
          values:
            packageName: '{{ index .path.segments 6 }}'
            clusterPurpose: '{{ index .path.segments 7 }}'
            environment: '{{ index .path.segments 8 }}'
            appsetName: 'infra-common'
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
              cluster-purpose: '{{ .values.clusterPurpose }}'
              environment-{{ .values.environment }}: "true"
  template:
    metadata:
      name: 'infra-{{ .name }}-{{ .values.environment }}-{{ .values.packageName }}'
      annotations:
        # See: https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#manifest-paths-annotation
        argocd.argoproj.io/manifest-generate-paths: .
      labels:
        cluster-purpose: '{{ .values.clusterPurpose }}'
        environment: '{{ index .metadata.labels "environment" }}'
        region: '{{ index .metadata.labels "region" }}'
        appset-name: '{{ .values.appsetName }}'
        package-name: '{{ .values.packageName }}'
        chart-name: '{{ dig "packagePathOrName" (printf "%s" (.values.packageName)) . }}'
    spec:
      project: "infra"
      sources:
      - repoURL: "{{ .chartRepoUrl }}"
        chart : '{{ dig "packagePathOrName" (printf "%s" (.values.packageName)) . }}'
        targetRevision: '{{ dig "chartVersionOverrideByClusterName" (.name) (printf "%s" (.chartVersion)) . }}'
        helm:
          releaseName: '{{ dig "releaseName" (printf "%s" (.values.packageName)) . }}'
          ignoreMissingValueFiles: true
          valueFiles:
          - '$values/values/operational/infra/{{ .values.packageName }}/values.yaml'
          - '$values/values/operational/infra/{{ .values.packageName }}/{{ .values.environment }}/values.yaml'
          - '$values/values/operational/infra/{{ .values.packageName }}/{{ .values.environment }}/{{ index .metadata.labels "region" }}/values.yaml'
          - '$values/values/operational/infra/{{ .values.packageName }}/{{ .values.environment }}/{{ index .metadata.labels "region" }}/{{ .name }}/values.yaml'
      - repoURL: 'https://github.com/Shaked/argocd-playground.git'
        targetRevision: HEAD
        ref: values
      destination:
        server: "{{ .server }}"
        namespace: '{{ dig "namespace" (printf "%s" (.values.packageName)) . }}'
  templatePatch: |
    spec:
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=orphan
    {{- if or (not (hasKey . "autoSync")) (and (hasKey . "autoSync") (hasKey .autoSync "enabled") .autoSync.enabled) }}
        automated:
          prune: {{ dig "autoSync" "prune" "false" . }}
          selfHeal: {{ dig "autoSync" "selfHeal" "false" . }}
    {{- end }}
    #   For disabling autosync as default
    #   if and (hasKey . "autoSync") (hasKey .autoSync "enabled")
    #   if .autoSync.enabled
    #   end