apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
    - repoURL: 'https://github.com/Shaked/argocd-playground'
      path: "argocd/projects"
      targetRevision: main
    - repoURL: 'https://github.com/Shaked/argocd-playground'
      path: "argocd/appsets/operational/infra"
      targetRevision: main
    - repoURL: 'https://github.com/Shaked/argocd-playground'
      path: "argocd/appsets/operational/apps"
      targetRevision: main
    - repoURL: 'https://github.com/Shaked/argocd-playground'
      path: "argocd/appsets/tests/infra"
      targetRevision: main
    - repoURL: 'https://github.com/Shaked/argocd-playground'
      path: "argocd/appsets/tests/apps"
      targetRevision: main
  destination:
    namespace: argocd
    name: dev04
