{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dummy1.fullname" . }}
  labels:
    {{- include "dummy1.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "dummy1.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "dummy1.selectorLabels" . | nindent 14 }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "dummy1.selectorLabels" . | nindent 14 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dummy1.fullname" . }}
  labels:
    {{- include "dummy1.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dummy1.fullname" . }}
  labels:
    {{- include "dummy1.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "dummy1.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "dummy1.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
